services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: bookcraft-postgres-build
    environment:
      POSTGRES_DB: bookcraft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - bookcraft_pg_data:/var/lib/postgresql/data
     
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bookcraft"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  bookcraft_pg_data: